version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: medidash_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medidash
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: node:18
    restart: unless-stopped
    working_dir: /backend
    volumes:
      - ./backend:/backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:medidash@postgres:5432/medidash_db
    ports:
      - "3001:3001"
    command: >
      bash -c "npm install 
      && npm start"
    depends_on:
      - postgres

volumes:
  postgres-data: