version: '3'

volumes:
  postgres-data:

networks:
  medidash-network:
    driver: bridge

services:
  postgres:
    image: postgres
    container_name: medidash-postgres
    restart: always
    environment:
      POSTGRES_DB: medidash_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medidash
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
    - medidash-network

  backend:
    image: node:18
    container_name: medidash-backend
    restart: unless-stopped
    working_dir: /backend
    volumes:
      - ./backend:/backend
      - ./logs/backend:/app/error.log
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:medidash@postgres:5432/medidash_db
    ports:
      - "3001:3001"
    command: >
      bash -c "npm install -g nodemon && npm run dev "
    depends_on:
      - postgres

  medidash:
    image: node:18
    container_name: medidash-app
    restart: unless-stopped
    working_dir: /medidash
    volumes:
      - ./medidash:/medidash
      - ./logs/medidash:/app/error.log
    environment:
      - NODE_ENV=production
    ports:
      - "3002:3002"
    command: >
      bash -c "PORT=3002 npm install && PORT=3002 npm start"    

