version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: medidash_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: medidash
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    image: node:14
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:medidash@postgres:5432/medidash_db
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres-data: